# -*- coding:utf-8 -*-
BUF_LEN = 2000
CBPY_BUF_LEN = 2000
OSCILLO_BUF_LEN = 2000
CBPY_TIMER_INTERVAL = 50        # ms
FETCH_TIMER_INTERVAL = 100      # ms
OSCILLO_TIMER_INTERVAL = 60     # ms
THRESH_PERCENTILE = 5.0
OUTLIER_THRESH_COEF = 1.5
FOCUS_RANGE = [10, 100]         # for mice
LOG_SAVE_PATH = '.'
